// <auto-generated />
namespace Foodtruck.Negocio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migracao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracao));
        
        string IMigrationMetadata.Id
        {
            get { return "201806072045392_migracao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
